### ISSUE TITLE
F-Droid Build 1.9 Targets Android 3.0

### ISSUE THREAD

**Issue by moriel5** [ympavlov/minidoro#2]
As the title says, version 1.9 of the F-Droid build targets Android 3.0, which prevents upgrades from 1.8 and displays warning that the app was made for older Android versions.

Originally found while verifying fix for issue #1.

**Comment by ympavlov** [comment]
Thank you. Will be fixed in upcoming 1.10 release

**Comment by ympavlov** [comment]
1.10 for Android 4.0+ became available in F-Droid. Please check. I'll try not to mix releases in the future

**Comment by moriel5** [comment]
Thanks, I'll go and test now. 

Update: I have verified that version 1.10 does indeed Target API14/Android 4.0.

Also, I have tested updating from 1.8 with invalid values renders the values inert, since Pomodoro ignores them, and falls back to the default values.

Interestingly, as long as the invalid values are still there, you can still insert invalid values (such as ".", "0" and ".."), however despite being accepted, they are still ignored, so although you could take the extra step of resetting the value to the default, it's not really a concern, since it doesn't affect anything, and the only users who would notice this would be those who did it on purpose, like me (probably no one).

**Comment by ympavlov** [comment]
Thanks, I think the values resetting would be an extra function that looks surplus since I try to keep code/app simple
