### ISSUE TITLE
Way to reset work counter?

### ISSUE THREAD

**Issue by b2ag** [ympavlov/minidoro#3]
Hi,

can I have an easy way to reset the work counter? I searched the source code but it looks like currently there is no way to reset it. I don't always stop using the App after a long break but want it to start with 4 cycles before a long break. And clearing app data everytime seems a bit much. Or did I miss something?

And I'm curious what the dash/quote counters are for?

I use your app for two days now and like it quite much so far. I used GoodTime for some month before but accendentally resetting stuff with guestures and not knowing how many work cycles I've already gone through (so not noticing an error guesture right away) drove me crazy. Also my single purpose Pomodoro phone seems to be to old for most of the other FOSS Pomodoro apps on F-Droid.

Last but not least: Please don't add "big" features to Minidoro! GoodTime for example can statistics and stuff I've never used but is really bad at doing simple things like UI right. It annoyed me so often when I triggered stuff with geastures by acciedent. Because of this I loved to see simple buttons and a confirmation dialog on your app. Keep on the good work!

Br,

**Comment by ympavlov** [comment]
Hi
Congratulations! You've clearly understood the concept!

Minidoro is partially inspired by Goodtime, and the fact Goodtime doesn't work on Android 5 was one of the reasons why Minidoro appeared. And I needed more simple and reliable tool. It's designed according to the best GUI design practices.
But Minidoro doesn't compete with Goodtime, Goodtime is preferred if more features are needed.

Back to the issue. It was assumed that swiping out a Minidoro task from recent task list should reset all the counters. Like this:
https://www.youtube.com/watch?v=VXDdmYVEQVs

If it's not enough I'll think to add something like context menu for work counter.

And probably, app stopping shouldn't reset counters, it may happen occasionally. I'll think about this too.

Thank you for participation. Please, let know here is you issue solved or not.

P. S. dash/quote counters are for accounting your distractions (when you distract yourself) and interruptions (when someone other distract or interrupt you). They invented in the original Pomodoro Technique book (you may buy it or find PDF in the internet).

**Comment by b2ag** [comment]
Ok. Got it. Thanks :heart:

**Comment by muziofg** [comment]
A context menu to reset/modify the pomodoro counter, like dash/quote counters, seems the correct way to make this app more similar to the interaction with physical devices (timer+paper)

I hope to see improvements from this app found on f-droid
