### ISSUE TITLE
[Feature Request] Ability to pause the timer

### ISSUE THREAD

**Issue by lihuelworks** [ympavlov/minidoro#9]
Just title. I've recently had to pause the timer for a bit to go to the bahtroom, but couldn't do it. I don't know if pausing it goes agains the Pomodoro Commandments, but a simple tap gestures to "pause" for non-consecuential interruptions would be great.

Sorry if I couldn't expand on the idea, it's 2am and I'm fresh out of braincells. Also, tysm  for the app, weirdly it's better at applying the wonderful concept of a simple timer than anything else I've seen on google store. Big props.

**Comment by ympavlov** [comment]
hank you for reply and sorry for big delay.

Minidoro follows the Pomodoro Technique very rigorously

According to the technique any small interuption shouldn't delay work nor affect the timer. You can only notice and count them by pressing ( ' ) button (it'll receive a proper description in upcoming #4). Also you can stop work timer if "you give in to temptation or something really urgent comes up" and start again later.

I appreciate your experience wtih Minidoro. But most probably, won't fix untill the concept changes
